### PR TITLE
Update customLightningDataTableController.cls

### PR DESCRIPTION
**Pull request by Hyphen8**

### CODE REVIEW

**Comment by Hyphen8** [comment]
Hi @danielbprobert, just updated this with an extra change. It allows you to have a formula field inside your field set when in edit mode.

Thanks, DT

**Comment by danielbprobert** [comment]
@DTHyphen8 merging this one in but can we make sure our commits and pulls requests are in each others names please

**Comment by DTHyphen8** [comment]
Sorted my credentials out for next time, thanks for merging

**Comment by danielbprobert** [comment]
package still needs generating

**Pull request merged**
